// Catálogo de países (ISO 3166-1 alfa-2, nombre corto en español) para el
// selector de país del cliente en Administración Mitrol (admin/tenants). Es
// DATO, no copy de interfaz — no se traduce por idioma (mismo criterio que
// los nombres de región en mock-admin.ts: "los países son dato").
export type Country = { id: string; nombre: string };

export const countries: Country[] = [
  { id: "AF", nombre: "Afganistán" },
  { id: "AL", nombre: "Albania" },
  { id: "DE", nombre: "Alemania" },
  { id: "AD", nombre: "Andorra" },
  { id: "AO", nombre: "Angola" },
  { id: "AG", nombre: "Antigua y Barbuda" },
  { id: "SA", nombre: "Arabia Saudita" },
  { id: "DZ", nombre: "Argelia" },
  { id: "AR", nombre: "Argentina" },
  { id: "AM", nombre: "Armenia" },
  { id: "AU", nombre: "Australia" },
  { id: "AT", nombre: "Austria" },
  { id: "AZ", nombre: "Azerbaiyán" },
  { id: "BS", nombre: "Bahamas" },
  { id: "BD", nombre: "Bangladés" },
  { id: "BB", nombre: "Barbados" },
  { id: "BH", nombre: "Baréin" },
  { id: "BE", nombre: "Bélgica" },
  { id: "BZ", nombre: "Belice" },
  { id: "BJ", nombre: "Benín" },
  { id: "BY", nombre: "Bielorrusia" },
  { id: "MM", nombre: "Birmania (Myanmar)" },
  { id: "BO", nombre: "Bolivia" },
  { id: "BA", nombre: "Bosnia y Herzegovina" },
  { id: "BW", nombre: "Botsuana" },
  { id: "BR", nombre: "Brasil" },
  { id: "BN", nombre: "Brunéi" },
  { id: "BG", nombre: "Bulgaria" },
  { id: "BF", nombre: "Burkina Faso" },
  { id: "BI", nombre: "Burundi" },
  { id: "BT", nombre: "Bután" },
  { id: "CV", nombre: "Cabo Verde" },
  { id: "KH", nombre: "Camboya" },
  { id: "CM", nombre: "Camerún" },
  { id: "CA", nombre: "Canadá" },
  { id: "QA", nombre: "Catar" },
  { id: "TD", nombre: "Chad" },
  { id: "CL", nombre: "Chile" },
  { id: "CN", nombre: "China" },
  { id: "CY", nombre: "Chipre" },
  { id: "VA", nombre: "Ciudad del Vaticano" },
  { id: "CO", nombre: "Colombia" },
  { id: "KM", nombre: "Comoras" },
  { id: "KP", nombre: "Corea del Norte" },
  { id: "KR", nombre: "Corea del Sur" },
  { id: "CI", nombre: "Costa de Marfil" },
  { id: "CR", nombre: "Costa Rica" },
  { id: "HR", nombre: "Croacia" },
  { id: "CU", nombre: "Cuba" },
  { id: "DK", nombre: "Dinamarca" },
  { id: "DM", nombre: "Dominica" },
  { id: "EC", nombre: "Ecuador" },
  { id: "EG", nombre: "Egipto" },
  { id: "SV", nombre: "El Salvador" },
  { id: "AE", nombre: "Emiratos Árabes Unidos" },
  { id: "ER", nombre: "Eritrea" },
  { id: "SK", nombre: "Eslovaquia" },
  { id: "SI", nombre: "Eslovenia" },
  { id: "ES", nombre: "España" },
  { id: "US", nombre: "Estados Unidos" },
  { id: "EE", nombre: "Estonia" },
  { id: "SZ", nombre: "Esuatini" },
  { id: "ET", nombre: "Etiopía" },
  { id: "PH", nombre: "Filipinas" },
  { id: "FI", nombre: "Finlandia" },
  { id: "FJ", nombre: "Fiyi" },
  { id: "FR", nombre: "Francia" },
  { id: "GA", nombre: "Gabón" },
  { id: "GM", nombre: "Gambia" },
  { id: "GE", nombre: "Georgia" },
  { id: "GH", nombre: "Ghana" },
  { id: "GD", nombre: "Granada" },
  { id: "GR", nombre: "Grecia" },
  { id: "GT", nombre: "Guatemala" },
  { id: "GN", nombre: "Guinea" },
  { id: "GW", nombre: "Guinea-Bisáu" },
  { id: "GQ", nombre: "Guinea Ecuatorial" },
  { id: "GY", nombre: "Guyana" },
  { id: "HT", nombre: "Haití" },
  { id: "HN", nombre: "Honduras" },
  { id: "HU", nombre: "Hungría" },
  { id: "IN", nombre: "India" },
  { id: "ID", nombre: "Indonesia" },
  { id: "IQ", nombre: "Irak" },
  { id: "IR", nombre: "Irán" },
  { id: "IE", nombre: "Irlanda" },
  { id: "IS", nombre: "Islandia" },
  { id: "MH", nombre: "Islas Marshall" },
  { id: "SB", nombre: "Islas Salomón" },
  { id: "IL", nombre: "Israel" },
  { id: "IT", nombre: "Italia" },
  { id: "JM", nombre: "Jamaica" },
  { id: "JP", nombre: "Japón" },
  { id: "JO", nombre: "Jordania" },
  { id: "KZ", nombre: "Kazajistán" },
  { id: "KE", nombre: "Kenia" },
  { id: "KG", nombre: "Kirguistán" },
  { id: "KI", nombre: "Kiribati" },
  { id: "KW", nombre: "Kuwait" },
  { id: "LA", nombre: "Laos" },
  { id: "LS", nombre: "Lesoto" },
  { id: "LV", nombre: "Letonia" },
  { id: "LB", nombre: "Líbano" },
  { id: "LR", nombre: "Liberia" },
  { id: "LY", nombre: "Libia" },
  { id: "LI", nombre: "Liechtenstein" },
  { id: "LT", nombre: "Lituania" },
  { id: "LU", nombre: "Luxemburgo" },
  { id: "MK", nombre: "Macedonia del Norte" },
  { id: "MG", nombre: "Madagascar" },
  { id: "MY", nombre: "Malasia" },
  { id: "MW", nombre: "Malaui" },
  { id: "MV", nombre: "Maldivas" },
  { id: "ML", nombre: "Malí" },
  { id: "MT", nombre: "Malta" },
  { id: "MA", nombre: "Marruecos" },
  { id: "MU", nombre: "Mauricio" },
  { id: "MR", nombre: "Mauritania" },
  { id: "MX", nombre: "México" },
  { id: "FM", nombre: "Micronesia" },
  { id: "MD", nombre: "Moldavia" },
  { id: "MC", nombre: "Mónaco" },
  { id: "MN", nombre: "Mongolia" },
  { id: "ME", nombre: "Montenegro" },
  { id: "MZ", nombre: "Mozambique" },
  { id: "NA", nombre: "Namibia" },
  { id: "NR", nombre: "Nauru" },
  { id: "NP", nombre: "Nepal" },
  { id: "NI", nombre: "Nicaragua" },
  { id: "NE", nombre: "Níger" },
  { id: "NG", nombre: "Nigeria" },
  { id: "NO", nombre: "Noruega" },
  { id: "NZ", nombre: "Nueva Zelanda" },
  { id: "OM", nombre: "Omán" },
  { id: "NL", nombre: "Países Bajos" },
  { id: "PK", nombre: "Pakistán" },
  { id: "PW", nombre: "Palaos" },
  { id: "PA", nombre: "Panamá" },
  { id: "PG", nombre: "Papúa Nueva Guinea" },
  { id: "PY", nombre: "Paraguay" },
  { id: "PE", nombre: "Perú" },
  { id: "PL", nombre: "Polonia" },
  { id: "PT", nombre: "Portugal" },
  { id: "GB", nombre: "Reino Unido" },
  { id: "CF", nombre: "República Centroafricana" },
  { id: "CZ", nombre: "República Checa" },
  { id: "CG", nombre: "República del Congo" },
  { id: "CD", nombre: "República Democrática del Congo" },
  { id: "DO", nombre: "República Dominicana" },
  { id: "RW", nombre: "Ruanda" },
  { id: "RO", nombre: "Rumania" },
  { id: "RU", nombre: "Rusia" },
  { id: "WS", nombre: "Samoa" },
  { id: "KN", nombre: "San Cristóbal y Nieves" },
  { id: "SM", nombre: "San Marino" },
  { id: "VC", nombre: "San Vicente y las Granadinas" },
  { id: "LC", nombre: "Santa Lucía" },
  { id: "ST", nombre: "Santo Tomé y Príncipe" },
  { id: "SN", nombre: "Senegal" },
  { id: "RS", nombre: "Serbia" },
  { id: "SC", nombre: "Seychelles" },
  { id: "SL", nombre: "Sierra Leona" },
  { id: "SG", nombre: "Singapur" },
  { id: "SY", nombre: "Siria" },
  { id: "SO", nombre: "Somalia" },
  { id: "LK", nombre: "Sri Lanka" },
  { id: "ZA", nombre: "Sudáfrica" },
  { id: "SD", nombre: "Sudán" },
  { id: "SS", nombre: "Sudán del Sur" },
  { id: "SE", nombre: "Suecia" },
  { id: "CH", nombre: "Suiza" },
  { id: "SR", nombre: "Surinam" },
  { id: "TH", nombre: "Tailandia" },
  { id: "TZ", nombre: "Tanzania" },
  { id: "TJ", nombre: "Tayikistán" },
  { id: "TL", nombre: "Timor Oriental" },
  { id: "TG", nombre: "Togo" },
  { id: "TO", nombre: "Tonga" },
  { id: "TT", nombre: "Trinidad y Tobago" },
  { id: "TN", nombre: "Túnez" },
  { id: "TM", nombre: "Turkmenistán" },
  { id: "TR", nombre: "Turquía" },
  { id: "TV", nombre: "Tuvalu" },
  { id: "UA", nombre: "Ucrania" },
  { id: "UG", nombre: "Uganda" },
  { id: "UY", nombre: "Uruguay" },
  { id: "UZ", nombre: "Uzbekistán" },
  { id: "VU", nombre: "Vanuatu" },
  { id: "VE", nombre: "Venezuela" },
  { id: "VN", nombre: "Vietnam" },
  { id: "YE", nombre: "Yemen" },
  { id: "DJ", nombre: "Yibuti" },
  { id: "ZM", nombre: "Zambia" },
  { id: "ZW", nombre: "Zimbabue" },
];

export function getCountry(id: string): Country | undefined {
  return countries.find((c) => c.id === id);
}
